# Generated by Django 3.2.4 on 2023-04-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music',
            field=models.FileField(default=0, upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
