# Generated by Django 3.2.4 on 2023-04-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20230403_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='music',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
