# Generated by Django 3.2.4 on 2023-04-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_song_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default=1, max_length=100000),
            preserve_default=False,
        ),
    ]
